% LAAS-CNRS: Robotic and Interaction Systems
% SICK LDMRS, Platine Light
% Harold F. MURCIA - October 2017

function [ J ] = model_E1( W, data_surf_1, data_surf_2, data_surf_3, data_surf_4, data_ground_1, data_ground_2, data_ground_3, data_ground_4 )
% input arguments: W= initial paramters, data_surf_1....4=segmented walls,
% data_ground_1 .... 4 segmented grounds from positions
%   Detailed explanation goes here
    
    % Intrinsic parameters (Extrinsic calibration implies to know the instrinsic parameters)
    L1z     =   0.103507895424538 ;
    L2x     =   -0.034172927080907;
    L2y     =   0.022677646649606;
    L2z     =   0.085483017579107;
    alpha1  =   -0.030480572343884;
    alpha2  =   -0.006887676801469;
    alpha3  =   0.007021913956145;
    alpha4  =   0.017831893165756;
    beta_off1 =-0.003260130399065;
    beta_off2  =0.001420077841539;

    % splitting by layers (colum 4 corresponds to layer information)
    layer_s1 = data_surf_1(:,4);  
    layer_s2 = data_surf_2(:,4);
    layer_s3 = data_surf_3(:,4);
    layer_s4 = data_surf_4(:,4);
    ALPHA_1=zeros(size(layer_s1));
    ALPHA_2=zeros(size(layer_s2));
    ALPHA_3=zeros(size(layer_s3));
    ALPHA_4=zeros(size(layer_s4));
    a1_s1=find(layer_s1==0);
    a2_s1=find(layer_s1==1);
    a3_s1=find(layer_s1==2);
    a4_s1=find(layer_s1==3);
    a1_s2=find(layer_s2==0);
    a2_s2=find(layer_s2==1);
    a3_s2=find(layer_s2==2);
    a4_s2=find(layer_s2==3);
    a1_s3=find(layer_s3==0);
    a2_s3=find(layer_s3==1);
    a3_s3=find(layer_s3==2);
    a4_s3=find(layer_s3==3);
    a1_s4=find(layer_s4==0);
    a2_s4=find(layer_s4==1);
    a3_s4=find(layer_s4==2);
    a4_s4=find(layer_s4==3);
    
    ALPHA_1(a1_s1)=alpha1; ALPHA_1(a2_s1)=alpha2; ALPHA_1(a3_s1)=alpha3; ALPHA_1(a4_s1)=alpha4;
    ALPHA_2(a1_s2)=alpha1; ALPHA_2(a2_s2)=alpha2; ALPHA_2(a3_s2)=alpha3; ALPHA_2(a4_s2)=alpha4;
    ALPHA_3(a1_s3)=alpha1; ALPHA_3(a2_s3)=alpha2; ALPHA_3(a3_s3)=alpha3; ALPHA_3(a4_s3)=alpha4;
    ALPHA_4(a1_s4)=alpha1; ALPHA_4(a2_s4)=alpha2; ALPHA_4(a3_s4)=alpha3; ALPHA_4(a4_s4)=alpha4;
    
    
    layer_s5 = data_ground_1(:,4);
    layer_s6 = data_ground_2(:,4);
    layer_s7 = data_ground_3(:,4);
    layer_s8 = data_ground_4(:,4);
    ALPHA_5=zeros(size(layer_s5));
    ALPHA_6=zeros(size(layer_s6));
    ALPHA_7=zeros(size(layer_s7));
    ALPHA_8=zeros(size(layer_s8));
    a1_s5=find(layer_s5==0);
    a2_s5=find(layer_s5==1);
    a3_s5=find(layer_s5==2);
    a4_s5=find(layer_s5==3);
    a1_s6=find(layer_s6==0);
    a2_s6=find(layer_s6==1);
    a3_s6=find(layer_s6==2);
    a4_s6=find(layer_s6==3);
    a1_s7=find(layer_s7==0);
    a2_s7=find(layer_s7==1);
    a3_s7=find(layer_s7==2);
    a4_s7=find(layer_s7==3);
    a1_s8=find(layer_s8==0);
    a2_s8=find(layer_s8==1);
    a3_s8=find(layer_s8==2);
    a4_s8=find(layer_s8==3);
    
    ALPHA_5(a1_s5)=alpha1; ALPHA_5(a2_s5)=alpha2; ALPHA_5(a3_s5)=alpha3; ALPHA_5(a4_s5)=alpha4;
    ALPHA_6(a1_s6)=alpha1; ALPHA_6(a2_s6)=alpha2; ALPHA_6(a3_s6)=alpha3; ALPHA_6(a4_s6)=alpha4;
    ALPHA_7(a1_s7)=alpha1; ALPHA_7(a2_s7)=alpha2; ALPHA_7(a3_s7)=alpha3; ALPHA_7(a4_s7)=alpha4;
    ALPHA_8(a1_s8)=alpha1; ALPHA_8(a2_s8)=alpha2; ALPHA_8(a3_s8)=alpha3; ALPHA_8(a4_s8)=alpha4;
    

    Minnie_Q_wxyz = [0.999999999274, 0, 0, -3.81075057872e-05; ...
                     0.967270826375, 0, 0, 0.253746228432;...
                     0.968700982599, 0, 0, -0.248230550721; ...
                     0.9999127301, 0, 0, .0132110629169];

    %Minnie_ang_z = atan2( 2*(Minnie_Q_wxyz(:,1).*Minnie_Q_wxyz(:,4) + Minnie_Q_wxyz(:,2).*Minnie_Q_wxyz(:,3)) , 1 + -2*(  Minnie_Q_wxyz(:,3).^2 +Minnie_Q_wxyz(:,4).^2) );
    [Minnie_pitch, Minnie_roll, Minnie_yaw] = quat2angle(Minnie_Q_wxyz(1:4,:),'YXZ');
    Minnie_yaw= -Minnie_yaw;
    
    Minnie_POS_XYZ=[-0.0011072741878 8.84206411503e-08 0; ...
                4.04728161632, -1.25454522771, 0; ...
                5.49540472942, 1.19624652699, 0;
                5.04887363497, -0.271461711511, 0];
    aux = Minnie_POS_XYZ(:,1);
    Minnie_POS_XYZ(:,1) = -Minnie_POS_XYZ(:,2);
    Minnie_POS_XYZ(:,2) = aux;

    % Data surf
    
    alpha_1 = ALPHA_1; alpha_2 = ALPHA_2; alpha_3 = ALPHA_3; alpha_4 = ALPHA_4;
    beta_1  = data_surf_1(:,3)+beta_off1; beta_2  = data_surf_2(:,3)+beta_off1;
    beta_3  = data_surf_3(:,3)+beta_off2; beta_4  = data_surf_4(:,3)+beta_off2;
    tilt_1  = data_surf_1(:,1); tilt_2  = data_surf_2(:,1);
    tilt_3  = data_surf_3(:,1); tilt_4  = data_surf_4(:,1);
    r_1     = data_surf_1(:,5); r_2     = data_surf_2(:,5); 
    r_3     = data_surf_3(:,5); r_4     = data_surf_4(:,5);
    
    ang_1   = -Minnie_yaw(1)*ones(size(layer_s1)); ang_2 = -Minnie_yaw(2)*ones(size(layer_s2));
    ang_3   = -Minnie_yaw(3)*ones(size(layer_s3)); ang_4 = -Minnie_yaw(4)*ones(size(layer_s4));
    off_x_1 = Minnie_POS_XYZ(1,1)*ones(size(layer_s1)); off_x_2 = Minnie_POS_XYZ(2,1)*ones(size(layer_s2));
    off_x_3 = Minnie_POS_XYZ(3,1)*ones(size(layer_s3)); off_x_4 = Minnie_POS_XYZ(4,1)*ones(size(layer_s4));
    off_y_1 = Minnie_POS_XYZ(1,2)*ones(size(layer_s1)); off_y_2 = Minnie_POS_XYZ(2,2)*ones(size(layer_s2));
    off_y_3 = Minnie_POS_XYZ(3,2)*ones(size(layer_s3)); off_y_4 = Minnie_POS_XYZ(4,2)*ones(size(layer_s4));
        
    % Data Ground
    
    alpha_5 = ALPHA_5; alpha_6 = ALPHA_6; alpha_7 = ALPHA_7; alpha_8 = ALPHA_8;
    beta_5  = data_ground_1(:,3)+beta_off1; beta_6  = data_ground_2(:,3)+beta_off1;
    beta_7  = data_ground_3(:,3)+beta_off2; beta_8  = data_ground_4(:,3)+beta_off2;
    tilt_5  = data_ground_1(:,1); tilt_6  = data_ground_2(:,1);
    tilt_7  = data_ground_3(:,1); tilt_8  = data_ground_4(:,1);
    r_5     = data_ground_1(:,5); r_6     = data_ground_2(:,5); 
    r_7     = data_ground_3(:,5); r_8     = data_ground_4(:,5);
    
    ang_5   = -Minnie_yaw(1)*ones(size(layer_s5)); ang_6 = -Minnie_yaw(2)*ones(size(layer_s6));
    ang_7   = -Minnie_yaw(3)*ones(size(layer_s7)); ang_8 = -Minnie_yaw(4)*ones(size(layer_s8));
    off_x_5 = Minnie_POS_XYZ(1,1)*ones(size(layer_s5)); off_x_6 = Minnie_POS_XYZ(2,1)*ones(size(layer_s6));
    off_x_7 = Minnie_POS_XYZ(3,1)*ones(size(layer_s7)); off_x_8 = Minnie_POS_XYZ(4,1)*ones(size(layer_s8));
    off_y_5 = Minnie_POS_XYZ(1,2)*ones(size(layer_s5)); off_y_6 = Minnie_POS_XYZ(2,2)*ones(size(layer_s6));
    off_y_7 = Minnie_POS_XYZ(3,2)*ones(size(layer_s7)); off_y_8 = Minnie_POS_XYZ(4,2)*ones(size(layer_s8));
     

    X_1 = off_x_1 + L2x.*(cos(W(5)).*(cos(ang_1).*cos(W(6)) - sin(ang_1).*sin(W(6))) - ...
        sin(W(4)).*sin(W(5)).*(cos(ang_1).*sin(W(6)) + sin(ang_1).*cos(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_1).*cos(W(6)) - sin(ang_1).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_1).*sin(W(6)) + sin(ang_1).*cos(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_1).*cos(W(6)) - sin(ang_1).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_1).*sin(W(6)) + sin(ang_1).*cos(W(6)))) + ...
        W(1).*cos(ang_1) - W(2).*sin(ang_1) - L2y.*cos(W(4)).*(cos(ang_1).*sin(W(6)) + ...
        sin(ang_1).*cos(W(6))) + r_1.*sin(alpha_1).*(cos(tilt_1).*(sin(W(5)).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_1).*sin(W(6)) + ...
        sin(ang_1).*cos(W(6)))) + cos(W(4)).*sin(tilt_1).*(cos(ang_1).*sin(W(6)) + ...
        sin(ang_1).*cos(W(6)))) - r_1.*cos(alpha_1).*sin(beta_1).*(cos(W(5)).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6))) - sin(W(4)).*sin(W(5)).*(cos(ang_1).*sin(W(6)) + ...
        sin(ang_1).*cos(W(6)))) + r_1.*cos(alpha_1).*cos(beta_1).*(sin(tilt_1).*(sin(W(5)).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_1).*sin(W(6)) + sin(ang_1).*cos(W(6)))) - ...
        cos(W(4)).*cos(tilt_1).*(cos(ang_1).*sin(W(6)) + sin(ang_1).*cos(W(6))));
 
    Y_1 = off_y_1 + L2x.*(cos(W(5)).*(cos(ang_1).*sin(W(6)) + sin(ang_1).*cos(W(6))) + ...
        sin(W(4)).*sin(W(5)).*(cos(ang_1).*cos(W(6)) - sin(ang_1).*sin(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_1).*sin(W(6)) + sin(ang_1).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_1).*cos(W(6)) - sin(ang_1).*sin(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_1).*sin(W(6)) + sin(ang_1).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_1).*cos(W(6)) - sin(ang_1).*sin(W(6)))) + ...
        W(2).*cos(ang_1) + W(1).*sin(ang_1) + L2y.*cos(W(4)).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6))) + r_1.*sin(alpha_1).*(cos(tilt_1).*(sin(W(5)).*(cos(ang_1).*sin(W(6)) + ...
        sin(ang_1).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6)))) - cos(W(4)).*sin(tilt_1).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6)))) - r_1.*cos(alpha_1).*sin(beta_1).*(cos(W(5)).*(cos(ang_1).*sin(W(6)) + ...
        sin(ang_1).*cos(W(6))) + sin(W(4)).*sin(W(5)).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6)))) + r_1.*cos(alpha_1).*cos(beta_1).*(sin(tilt_1).*(sin(W(5)).*(cos(ang_1).*sin(W(6)) + ...
        sin(ang_1).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6)))) + cos(W(4)).*cos(tilt_1).*(cos(ang_1).*cos(W(6)) - ...
        sin(ang_1).*sin(W(6))));
    
    Z_1 = W(3) + L2y.*sin(W(4)) - r_1.*sin(alpha_1).*(sin(W(4)).*sin(tilt_1) - ...
        cos(W(4)).*cos(W(5)).*cos(tilt_1)) + L1z.*cos(W(4)).*cos(W(5)) + ...
        L2z.*cos(W(4)).*cos(W(5)) - L2x.*cos(W(4)).*sin(W(5)) + ...
        r_1.*cos(alpha_1).*cos(beta_1).*(cos(tilt_1).*sin(W(4)) + cos(W(4)).*cos(W(5)).*sin(tilt_1)) + ...
        r_1.*cos(alpha_1).*cos(W(4)).*sin(beta_1).*sin(W(5));
    
    X_2 = off_x_2 + L2x.*(cos(W(5)).*(cos(ang_2).*cos(W(6)) - sin(ang_2).*sin(W(6))) - ...
        sin(W(4)).*sin(W(5)).*(cos(ang_2).*sin(W(6)) + sin(ang_2).*cos(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_2).*cos(W(6)) - sin(ang_2).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_2).*sin(W(6)) + sin(ang_2).*cos(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_2).*cos(W(6)) - sin(ang_2).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_2).*sin(W(6)) + sin(ang_2).*cos(W(6)))) + ...
        W(1).*cos(ang_2) - W(2).*sin(ang_2) - L2y.*cos(W(4)).*(cos(ang_2).*sin(W(6)) + ...
        sin(ang_2).*cos(W(6))) + r_2.*sin(alpha_2).*(cos(tilt_2).*(sin(W(5)).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_2).*sin(W(6)) + ...
        sin(ang_2).*cos(W(6)))) + cos(W(4)).*sin(tilt_2).*(cos(ang_2).*sin(W(6)) + ...
        sin(ang_2).*cos(W(6)))) - r_2.*cos(alpha_2).*sin(beta_2).*(cos(W(5)).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6))) - sin(W(4)).*sin(W(5)).*(cos(ang_2).*sin(W(6)) + ...
        sin(ang_2).*cos(W(6)))) + r_2.*cos(alpha_2).*cos(beta_2).*(sin(tilt_2).*(sin(W(5)).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_2).*sin(W(6)) + sin(ang_2).*cos(W(6)))) - ...
        cos(W(4)).*cos(tilt_2).*(cos(ang_2).*sin(W(6)) + sin(ang_2).*cos(W(6))));
 
    Y_2 = off_y_2 + L2x.*(cos(W(5)).*(cos(ang_2).*sin(W(6)) + sin(ang_2).*cos(W(6))) + ...
        sin(W(4)).*sin(W(5)).*(cos(ang_2).*cos(W(6)) - sin(ang_2).*sin(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_2).*sin(W(6)) + sin(ang_2).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_2).*cos(W(6)) - sin(ang_2).*sin(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_2).*sin(W(6)) + sin(ang_2).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_2).*cos(W(6)) - sin(ang_2).*sin(W(6)))) + ...
        W(2).*cos(ang_2) + W(1).*sin(ang_2) + L2y.*cos(W(4)).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6))) + r_2.*sin(alpha_2).*(cos(tilt_2).*(sin(W(5)).*(cos(ang_2).*sin(W(6)) + ...
        sin(ang_2).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6)))) - cos(W(4)).*sin(tilt_2).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6)))) - r_2.*cos(alpha_2).*sin(beta_2).*(cos(W(5)).*(cos(ang_2).*sin(W(6)) + ...
        sin(ang_2).*cos(W(6))) + sin(W(4)).*sin(W(5)).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6)))) + r_2.*cos(alpha_2).*cos(beta_2).*(sin(tilt_2).*(sin(W(5)).*(cos(ang_2).*sin(W(6)) + ...
        sin(ang_2).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6)))) + cos(W(4)).*cos(tilt_2).*(cos(ang_2).*cos(W(6)) - ...
        sin(ang_2).*sin(W(6))));
    
    Z_2 = W(3) + L2y.*sin(W(4)) - r_2.*sin(alpha_2).*(sin(W(4)).*sin(tilt_2) - ...
        cos(W(4)).*cos(W(5)).*cos(tilt_2)) + L1z.*cos(W(4)).*cos(W(5)) + ...
        L2z.*cos(W(4)).*cos(W(5)) - L2x.*cos(W(4)).*sin(W(5)) + ...
        r_2.*cos(alpha_2).*cos(beta_2).*(cos(tilt_2).*sin(W(4)) + cos(W(4)).*cos(W(5)).*sin(tilt_2)) + ...
        r_2.*cos(alpha_2).*cos(W(4)).*sin(beta_2).*sin(W(5));
    
    X_3 = off_x_3 + L2x.*(cos(W(5)).*(cos(ang_3).*cos(W(6)) - sin(ang_3).*sin(W(6))) - ...
        sin(W(4)).*sin(W(5)).*(cos(ang_3).*sin(W(6)) + sin(ang_3).*cos(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_3).*cos(W(6)) - sin(ang_3).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_3).*sin(W(6)) + sin(ang_3).*cos(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_3).*cos(W(6)) - sin(ang_3).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_3).*sin(W(6)) + sin(ang_3).*cos(W(6)))) + ...
        W(1).*cos(ang_3) - W(2).*sin(ang_3) - L2y.*cos(W(4)).*(cos(ang_3).*sin(W(6)) + ...
        sin(ang_3).*cos(W(6))) + r_3.*sin(alpha_3).*(cos(tilt_3).*(sin(W(5)).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_3).*sin(W(6)) + ...
        sin(ang_3).*cos(W(6)))) + cos(W(4)).*sin(tilt_3).*(cos(ang_3).*sin(W(6)) + ...
        sin(ang_3).*cos(W(6)))) - r_3.*cos(alpha_3).*sin(beta_3).*(cos(W(5)).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6))) - sin(W(4)).*sin(W(5)).*(cos(ang_3).*sin(W(6)) + ...
        sin(ang_3).*cos(W(6)))) + r_3.*cos(alpha_3).*cos(beta_3).*(sin(tilt_3).*(sin(W(5)).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_3).*sin(W(6)) + sin(ang_3).*cos(W(6)))) - ...
        cos(W(4)).*cos(tilt_3).*(cos(ang_3).*sin(W(6)) + sin(ang_3).*cos(W(6))));
 
    Y_3 = off_y_3 + L2x.*(cos(W(5)).*(cos(ang_3).*sin(W(6)) + sin(ang_3).*cos(W(6))) + ...
        sin(W(4)).*sin(W(5)).*(cos(ang_3).*cos(W(6)) - sin(ang_3).*sin(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_3).*sin(W(6)) + sin(ang_3).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_3).*cos(W(6)) - sin(ang_3).*sin(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_3).*sin(W(6)) + sin(ang_3).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_3).*cos(W(6)) - sin(ang_3).*sin(W(6)))) + ...
        W(2).*cos(ang_3) + W(1).*sin(ang_3) + L2y.*cos(W(4)).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6))) + r_3.*sin(alpha_3).*(cos(tilt_3).*(sin(W(5)).*(cos(ang_3).*sin(W(6)) + ...
        sin(ang_3).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6)))) - cos(W(4)).*sin(tilt_3).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6)))) - r_3.*cos(alpha_3).*sin(beta_3).*(cos(W(5)).*(cos(ang_3).*sin(W(6)) + ...
        sin(ang_3).*cos(W(6))) + sin(W(4)).*sin(W(5)).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6)))) + r_3.*cos(alpha_3).*cos(beta_3).*(sin(tilt_3).*(sin(W(5)).*(cos(ang_3).*sin(W(6)) + ...
        sin(ang_3).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6)))) + cos(W(4)).*cos(tilt_3).*(cos(ang_3).*cos(W(6)) - ...
        sin(ang_3).*sin(W(6))));
    
    Z_3 = W(3) + L2y.*sin(W(4)) - r_3.*sin(alpha_3).*(sin(W(4)).*sin(tilt_3) - ...
        cos(W(4)).*cos(W(5)).*cos(tilt_3)) + L1z.*cos(W(4)).*cos(W(5)) + ...
        L2z.*cos(W(4)).*cos(W(5)) - L2x.*cos(W(4)).*sin(W(5)) + ...
        r_3.*cos(alpha_3).*cos(beta_3).*(cos(tilt_3).*sin(W(4)) + cos(W(4)).*cos(W(5)).*sin(tilt_3)) + ...
        r_3.*cos(alpha_3).*cos(W(4)).*sin(beta_3).*sin(W(5));
    
    
    X_4 = off_x_4 + L2x.*(cos(W(5)).*(cos(ang_4).*cos(W(6)) - sin(ang_4).*sin(W(6))) - ...
        sin(W(4)).*sin(W(5)).*(cos(ang_4).*sin(W(6)) + sin(ang_4).*cos(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_4).*cos(W(6)) - sin(ang_4).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_4).*sin(W(6)) + sin(ang_4).*cos(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_4).*cos(W(6)) - sin(ang_4).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_4).*sin(W(6)) + sin(ang_4).*cos(W(6)))) + ...
        W(1).*cos(ang_4) - W(2).*sin(ang_4) - L2y.*cos(W(4)).*(cos(ang_4).*sin(W(6)) + ...
        sin(ang_4).*cos(W(6))) + r_4.*sin(alpha_4).*(cos(tilt_4).*(sin(W(5)).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_4).*sin(W(6)) + ...
        sin(ang_4).*cos(W(6)))) + cos(W(4)).*sin(tilt_4).*(cos(ang_4).*sin(W(6)) + ...
        sin(ang_4).*cos(W(6)))) - r_4.*cos(alpha_4).*sin(beta_4).*(cos(W(5)).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6))) - sin(W(4)).*sin(W(5)).*(cos(ang_4).*sin(W(6)) + ...
        sin(ang_4).*cos(W(6)))) + r_4.*cos(alpha_4).*cos(beta_4).*(sin(tilt_4).*(sin(W(5)).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_4).*sin(W(6)) + sin(ang_4).*cos(W(6)))) - ...
        cos(W(4)).*cos(tilt_4).*(cos(ang_4).*sin(W(6)) + sin(ang_4).*cos(W(6))));
 
    Y_4 = off_y_4 + L2x.*(cos(W(5)).*(cos(ang_4).*sin(W(6)) + sin(ang_4).*cos(W(6))) + ...
        sin(W(4)).*sin(W(5)).*(cos(ang_4).*cos(W(6)) - sin(ang_4).*sin(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_4).*sin(W(6)) + sin(ang_4).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_4).*cos(W(6)) - sin(ang_4).*sin(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_4).*sin(W(6)) + sin(ang_4).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_4).*cos(W(6)) - sin(ang_4).*sin(W(6)))) + ...
        W(2).*cos(ang_4) + W(1).*sin(ang_4) + L2y.*cos(W(4)).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6))) + r_4.*sin(alpha_4).*(cos(tilt_4).*(sin(W(5)).*(cos(ang_4).*sin(W(6)) + ...
        sin(ang_4).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6)))) - cos(W(4)).*sin(tilt_4).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6)))) - r_4.*cos(alpha_4).*sin(beta_4).*(cos(W(5)).*(cos(ang_4).*sin(W(6)) + ...
        sin(ang_4).*cos(W(6))) + sin(W(4)).*sin(W(5)).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6)))) + r_4.*cos(alpha_4).*cos(beta_4).*(sin(tilt_4).*(sin(W(5)).*(cos(ang_4).*sin(W(6)) + ...
        sin(ang_4).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6)))) + cos(W(4)).*cos(tilt_4).*(cos(ang_4).*cos(W(6)) - ...
        sin(ang_4).*sin(W(6))));
    
    Z_4 = W(3) + L2y.*sin(W(4)) - r_4.*sin(alpha_4).*(sin(W(4)).*sin(tilt_4) - ...
        cos(W(4)).*cos(W(5)).*cos(tilt_4)) + L1z.*cos(W(4)).*cos(W(5)) + ...
        L2z.*cos(W(4)).*cos(W(5)) - L2x.*cos(W(4)).*sin(W(5)) + ...
        r_4.*cos(alpha_4).*cos(beta_4).*(cos(tilt_4).*sin(W(4)) + cos(W(4)).*cos(W(5)).*sin(tilt_4)) + ...
        r_4.*cos(alpha_4).*cos(W(4)).*sin(beta_4).*sin(W(5));
    
    
    X_5 = off_x_5 + L2x.*(cos(W(5)).*(cos(ang_5).*cos(W(6)) - sin(ang_5).*sin(W(6))) - ...
        sin(W(4)).*sin(W(5)).*(cos(ang_5).*sin(W(6)) + sin(ang_5).*cos(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_5).*cos(W(6)) - sin(ang_5).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_5).*sin(W(6)) + sin(ang_5).*cos(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_5).*cos(W(6)) - sin(ang_5).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_5).*sin(W(6)) + sin(ang_5).*cos(W(6)))) + ...
        W(1).*cos(ang_5) - W(2).*sin(ang_5) - L2y.*cos(W(4)).*(cos(ang_5).*sin(W(6)) + ...
        sin(ang_5).*cos(W(6))) + r_5.*sin(alpha_5).*(cos(tilt_5).*(sin(W(5)).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_5).*sin(W(6)) + ...
        sin(ang_5).*cos(W(6)))) + cos(W(4)).*sin(tilt_5).*(cos(ang_5).*sin(W(6)) + ...
        sin(ang_5).*cos(W(6)))) - r_5.*cos(alpha_5).*sin(beta_5).*(cos(W(5)).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6))) - sin(W(4)).*sin(W(5)).*(cos(ang_5).*sin(W(6)) + ...
        sin(ang_5).*cos(W(6)))) + r_5.*cos(alpha_5).*cos(beta_5).*(sin(tilt_5).*(sin(W(5)).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_5).*sin(W(6)) + sin(ang_5).*cos(W(6)))) - ...
        cos(W(4)).*cos(tilt_5).*(cos(ang_5).*sin(W(6)) + sin(ang_5).*cos(W(6))));
 
    Y_5 = off_y_5 + L2x.*(cos(W(5)).*(cos(ang_5).*sin(W(6)) + sin(ang_5).*cos(W(6))) + ...
        sin(W(4)).*sin(W(5)).*(cos(ang_5).*cos(W(6)) - sin(ang_5).*sin(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_5).*sin(W(6)) + sin(ang_5).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_5).*cos(W(6)) - sin(ang_5).*sin(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_5).*sin(W(6)) + sin(ang_5).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_5).*cos(W(6)) - sin(ang_5).*sin(W(6)))) + ...
        W(2).*cos(ang_5) + W(1).*sin(ang_5) + L2y.*cos(W(4)).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6))) + r_5.*sin(alpha_5).*(cos(tilt_5).*(sin(W(5)).*(cos(ang_5).*sin(W(6)) + ...
        sin(ang_5).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6)))) - cos(W(4)).*sin(tilt_5).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6)))) - r_5.*cos(alpha_5).*sin(beta_5).*(cos(W(5)).*(cos(ang_5).*sin(W(6)) + ...
        sin(ang_5).*cos(W(6))) + sin(W(4)).*sin(W(5)).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6)))) + r_5.*cos(alpha_5).*cos(beta_5).*(sin(tilt_5).*(sin(W(5)).*(cos(ang_5).*sin(W(6)) + ...
        sin(ang_5).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6)))) + cos(W(4)).*cos(tilt_5).*(cos(ang_5).*cos(W(6)) - ...
        sin(ang_5).*sin(W(6))));
    
    Z_5 = W(3) + L2y.*sin(W(4)) - r_5.*sin(alpha_5).*(sin(W(4)).*sin(tilt_5) - ...
        cos(W(4)).*cos(W(5)).*cos(tilt_5)) + L1z.*cos(W(4)).*cos(W(5)) + ...
        L2z.*cos(W(4)).*cos(W(5)) - L2x.*cos(W(4)).*sin(W(5)) + ...
        r_5.*cos(alpha_5).*cos(beta_5).*(cos(tilt_5).*sin(W(4)) + cos(W(4)).*cos(W(5)).*sin(tilt_5)) + ...
        r_5.*cos(alpha_5).*cos(W(4)).*sin(beta_5).*sin(W(5));
    
    X_6 = off_x_6 + L2x.*(cos(W(5)).*(cos(ang_6).*cos(W(6)) - sin(ang_6).*sin(W(6))) - ...
        sin(W(4)).*sin(W(5)).*(cos(ang_6).*sin(W(6)) + sin(ang_6).*cos(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_6).*cos(W(6)) - sin(ang_6).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_6).*sin(W(6)) + sin(ang_6).*cos(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_6).*cos(W(6)) - sin(ang_6).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_6).*sin(W(6)) + sin(ang_6).*cos(W(6)))) + ...
        W(1).*cos(ang_6) - W(2).*sin(ang_6) - L2y.*cos(W(4)).*(cos(ang_6).*sin(W(6)) + ...
        sin(ang_6).*cos(W(6))) + r_6.*sin(alpha_6).*(cos(tilt_6).*(sin(W(5)).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_6).*sin(W(6)) + ...
        sin(ang_6).*cos(W(6)))) + cos(W(4)).*sin(tilt_6).*(cos(ang_6).*sin(W(6)) + ...
        sin(ang_6).*cos(W(6)))) - r_6.*cos(alpha_6).*sin(beta_6).*(cos(W(5)).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6))) - sin(W(4)).*sin(W(5)).*(cos(ang_6).*sin(W(6)) + ...
        sin(ang_6).*cos(W(6)))) + r_6.*cos(alpha_6).*cos(beta_6).*(sin(tilt_6).*(sin(W(5)).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_6).*sin(W(6)) + sin(ang_6).*cos(W(6)))) - ...
        cos(W(4)).*cos(tilt_6).*(cos(ang_6).*sin(W(6)) + sin(ang_6).*cos(W(6))));
 
    Y_6 = off_y_6 + L2x.*(cos(W(5)).*(cos(ang_6).*sin(W(6)) + sin(ang_6).*cos(W(6))) + ...
        sin(W(4)).*sin(W(5)).*(cos(ang_6).*cos(W(6)) - sin(ang_6).*sin(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_6).*sin(W(6)) + sin(ang_6).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_6).*cos(W(6)) - sin(ang_6).*sin(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_6).*sin(W(6)) + sin(ang_6).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_6).*cos(W(6)) - sin(ang_6).*sin(W(6)))) + ...
        W(2).*cos(ang_6) + W(1).*sin(ang_6) + L2y.*cos(W(4)).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6))) + r_6.*sin(alpha_6).*(cos(tilt_6).*(sin(W(5)).*(cos(ang_6).*sin(W(6)) + ...
        sin(ang_6).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6)))) - cos(W(4)).*sin(tilt_6).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6)))) - r_6.*cos(alpha_6).*sin(beta_6).*(cos(W(5)).*(cos(ang_6).*sin(W(6)) + ...
        sin(ang_6).*cos(W(6))) + sin(W(4)).*sin(W(5)).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6)))) + r_6.*cos(alpha_6).*cos(beta_6).*(sin(tilt_6).*(sin(W(5)).*(cos(ang_6).*sin(W(6)) + ...
        sin(ang_6).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6)))) + cos(W(4)).*cos(tilt_6).*(cos(ang_6).*cos(W(6)) - ...
        sin(ang_6).*sin(W(6))));
    
    Z_6 = W(3) + L2y.*sin(W(4)) - r_6.*sin(alpha_6).*(sin(W(4)).*sin(tilt_6) - ...
        cos(W(4)).*cos(W(5)).*cos(tilt_6)) + L1z.*cos(W(4)).*cos(W(5)) + ...
        L2z.*cos(W(4)).*cos(W(5)) - L2x.*cos(W(4)).*sin(W(5)) + ...
        r_6.*cos(alpha_6).*cos(beta_6).*(cos(tilt_6).*sin(W(4)) + cos(W(4)).*cos(W(5)).*sin(tilt_6)) + ...
        r_6.*cos(alpha_6).*cos(W(4)).*sin(beta_6).*sin(W(5));
    
    X_7 = off_x_7 + L2x.*(cos(W(5)).*(cos(ang_7).*cos(W(6)) - sin(ang_7).*sin(W(6))) - ...
        sin(W(4)).*sin(W(5)).*(cos(ang_7).*sin(W(6)) + sin(ang_7).*cos(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_7).*cos(W(6)) - sin(ang_7).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_7).*sin(W(6)) + sin(ang_7).*cos(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_7).*cos(W(6)) - sin(ang_7).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_7).*sin(W(6)) + sin(ang_7).*cos(W(6)))) + ...
        W(1).*cos(ang_7) - W(2).*sin(ang_7) - L2y.*cos(W(4)).*(cos(ang_7).*sin(W(6)) + ...
        sin(ang_7).*cos(W(6))) + r_7.*sin(alpha_7).*(cos(tilt_7).*(sin(W(5)).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_7).*sin(W(6)) + ...
        sin(ang_7).*cos(W(6)))) + cos(W(4)).*sin(tilt_7).*(cos(ang_7).*sin(W(6)) + ...
        sin(ang_7).*cos(W(6)))) - r_7.*cos(alpha_7).*sin(beta_7).*(cos(W(5)).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6))) - sin(W(4)).*sin(W(5)).*(cos(ang_7).*sin(W(6)) + ...
        sin(ang_7).*cos(W(6)))) + r_7.*cos(alpha_7).*cos(beta_7).*(sin(tilt_7).*(sin(W(5)).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_7).*sin(W(6)) + sin(ang_7).*cos(W(6)))) - ...
        cos(W(4)).*cos(tilt_7).*(cos(ang_7).*sin(W(6)) + sin(ang_7).*cos(W(6))));
 
    Y_7 = off_y_7 + L2x.*(cos(W(5)).*(cos(ang_7).*sin(W(6)) + sin(ang_7).*cos(W(6))) + ...
        sin(W(4)).*sin(W(5)).*(cos(ang_7).*cos(W(6)) - sin(ang_7).*sin(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_7).*sin(W(6)) + sin(ang_7).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_7).*cos(W(6)) - sin(ang_7).*sin(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_7).*sin(W(6)) + sin(ang_7).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_7).*cos(W(6)) - sin(ang_7).*sin(W(6)))) + ...
        W(2).*cos(ang_7) + W(1).*sin(ang_7) + L2y.*cos(W(4)).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6))) + r_7.*sin(alpha_7).*(cos(tilt_7).*(sin(W(5)).*(cos(ang_7).*sin(W(6)) + ...
        sin(ang_7).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6)))) - cos(W(4)).*sin(tilt_7).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6)))) - r_7.*cos(alpha_7).*sin(beta_7).*(cos(W(5)).*(cos(ang_7).*sin(W(6)) + ...
        sin(ang_7).*cos(W(6))) + sin(W(4)).*sin(W(5)).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6)))) + r_7.*cos(alpha_7).*cos(beta_7).*(sin(tilt_7).*(sin(W(5)).*(cos(ang_7).*sin(W(6)) + ...
        sin(ang_7).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6)))) + cos(W(4)).*cos(tilt_7).*(cos(ang_7).*cos(W(6)) - ...
        sin(ang_7).*sin(W(6))));
    
    Z_7 = W(3) + L2y.*sin(W(4)) - r_7.*sin(alpha_7).*(sin(W(4)).*sin(tilt_7) - ...
        cos(W(4)).*cos(W(5)).*cos(tilt_7)) + L1z.*cos(W(4)).*cos(W(5)) + ...
        L2z.*cos(W(4)).*cos(W(5)) - L2x.*cos(W(4)).*sin(W(5)) + ...
        r_7.*cos(alpha_7).*cos(beta_7).*(cos(tilt_7).*sin(W(4)) + cos(W(4)).*cos(W(5)).*sin(tilt_7)) + ...
        r_7.*cos(alpha_7).*cos(W(4)).*sin(beta_7).*sin(W(5));
    
    X_8 = off_x_8 + L2x.*(cos(W(5)).*(cos(ang_8).*cos(W(6)) - sin(ang_8).*sin(W(6))) - ...
        sin(W(4)).*sin(W(5)).*(cos(ang_8).*sin(W(6)) + sin(ang_8).*cos(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_8).*cos(W(6)) - sin(ang_8).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_8).*sin(W(6)) + sin(ang_8).*cos(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_8).*cos(W(6)) - sin(ang_8).*sin(W(6))) + ...
        cos(W(5)).*sin(W(4)).*(cos(ang_8).*sin(W(6)) + sin(ang_8).*cos(W(6)))) + ...
        W(1).*cos(ang_8) - W(2).*sin(ang_8) - L2y.*cos(W(4)).*(cos(ang_8).*sin(W(6)) + ...
        sin(ang_8).*cos(W(6))) + r_8.*sin(alpha_8).*(cos(tilt_8).*(sin(W(5)).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_8).*sin(W(6)) + ...
        sin(ang_8).*cos(W(6)))) + cos(W(4)).*sin(tilt_8).*(cos(ang_8).*sin(W(6)) + ...
        sin(ang_8).*cos(W(6)))) - r_8.*cos(alpha_8).*sin(beta_8).*(cos(W(5)).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6))) - sin(W(4)).*sin(W(5)).*(cos(ang_8).*sin(W(6)) + ...
        sin(ang_8).*cos(W(6)))) + r_8.*cos(alpha_8).*cos(beta_8).*(sin(tilt_8).*(sin(W(5)).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6))) + cos(W(5)).*sin(W(4)).*(cos(ang_8).*sin(W(6)) + sin(ang_8).*cos(W(6)))) - ...
        cos(W(4)).*cos(tilt_8).*(cos(ang_8).*sin(W(6)) + sin(ang_8).*cos(W(6))));
 
    Y_8 = off_y_8 + L2x.*(cos(W(5)).*(cos(ang_8).*sin(W(6)) + sin(ang_8).*cos(W(6))) + ...
        sin(W(4)).*sin(W(5)).*(cos(ang_8).*cos(W(6)) - sin(ang_8).*sin(W(6)))) + ...
        L1z.*(sin(W(5)).*(cos(ang_8).*sin(W(6)) + sin(ang_8).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_8).*cos(W(6)) - sin(ang_8).*sin(W(6)))) + ...
        L2z.*(sin(W(5)).*(cos(ang_8).*sin(W(6)) + sin(ang_8).*cos(W(6))) - ...
        cos(W(5)).*sin(W(4)).*(cos(ang_8).*cos(W(6)) - sin(ang_8).*sin(W(6)))) + ...
        W(2).*cos(ang_8) + W(1).*sin(ang_8) + L2y.*cos(W(4)).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6))) + r_8.*sin(alpha_8).*(cos(tilt_8).*(sin(W(5)).*(cos(ang_8).*sin(W(6)) + ...
        sin(ang_8).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6)))) - cos(W(4)).*sin(tilt_8).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6)))) - r_8.*cos(alpha_8).*sin(beta_8).*(cos(W(5)).*(cos(ang_8).*sin(W(6)) + ...
        sin(ang_8).*cos(W(6))) + sin(W(4)).*sin(W(5)).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6)))) + r_8.*cos(alpha_8).*cos(beta_8).*(sin(tilt_8).*(sin(W(5)).*(cos(ang_8).*sin(W(6)) + ...
        sin(ang_8).*cos(W(6))) - cos(W(5)).*sin(W(4)).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6)))) + cos(W(4)).*cos(tilt_8).*(cos(ang_8).*cos(W(6)) - ...
        sin(ang_8).*sin(W(6))));
    
    Z_8 = W(3) + L2y.*sin(W(4)) - r_8.*sin(alpha_8).*(sin(W(4)).*sin(tilt_8) - ...
        cos(W(4)).*cos(W(5)).*cos(tilt_8)) + L1z.*cos(W(4)).*cos(W(5)) + ...
        L2z.*cos(W(4)).*cos(W(5)) - L2x.*cos(W(4)).*sin(W(5)) + ...
        r_8.*cos(alpha_8).*cos(beta_8).*(cos(tilt_8).*sin(W(4)) + cos(W(4)).*cos(W(5)).*sin(tilt_8)) + ...
        r_8.*cos(alpha_8).*cos(W(4)).*sin(beta_8).*sin(W(5));
    
    % Estimating planes for the wall reference in each position data-set
        M_1 = [ones(size(X_1)), X_1, Z_1];
        K1  = lscov(M_1,Y_1);
        M_2 = [ones(size(X_2)), X_2, Z_2];
        K2  = lscov(M_2,Y_2);
        M_3 = [ones(size(X_3)), X_3, Z_3];
        K3  = lscov(M_3,Y_3);
        M_4 = [ones(size(X_4)), X_4, Z_4];
        K4  = lscov(M_4,Y_4);
    
    F  =  (K1(1) - K2(1))^2 + (K1(2) - K2(2))^2 + (K1(3) - K2(3))^2 + ...
        (K1(1) - K3(1))^2 + (K1(2) - K3(2))^2 + (K1(3) - K3(3))^2 + ...
        (K3(1) - K2(1))^2 + (K3(2) - K2(2))^2 + (K3(3) - K2(3))^2;
    
    % Estimating planes for the ground reference in each position data-set
    M_5 = [ones(size(X_5)), X_5, Y_5];
    K5  = lscov(M_5,Z_5);
    M_6 = [ones(size(X_6)), X_6, Y_6];
    K6  = lscov(M_6,Z_6);
    M_7 = [ones(size(X_7)), X_7, Y_7];
    K7  = lscov(M_7,Z_7);
    M_8 = [ones(size(X_8)), X_8, Y_8];
    K8  = lscov(M_8,Z_8);
    
    Xmin_G = min([min(X_5) min(X_6) min(X_7) min(X_8)]);
    Xmax_G = min([max(X_5) max(X_6) max(X_7) max(X_8)]);
    Ymin_G = min([min(Y_5) min(Y_6) min(Y_7) min(Y_8)]);
    Ymax_G = min([max(Y_5) max(Y_6) max(Y_7) max(Y_8)]);
    
    L = 5e3; % L is an arbitary number to fix the length of the ground data at the same value
    X = Xmin_G:(Xmax_G-Xmin_G)/L:Xmax_G;
    Y = Ymin_G:(Ymax_G-Ymin_G)/L:Ymax_G;
    F5 = sum( ( K5(1) +K5(2)*X + K5(3)*Y + K6(1) +K6(2)*X + K6(3)*Y +...
        K7(1) +K7(2)*X + K7(3)*Y + K8(1) +K8(2)*X + K8(3)*Y ).^2 );
    
    % Cost functions
    J = [F; F5];
    
end

